{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-watchdog-pod-delete.serviceAccountName" . }}
  labels:
    {{- include "helm-watchdog-pod-delete.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-watchdog-pod-delete.serviceAccountName" . }}
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["create","get", "list", "delete","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm-watchdog-pod-delete.serviceAccountName" . }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "helm-watchdog-pod-delete.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "helm-watchdog-pod-delete.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
